### ISSUE TITLE
Examples don't work because ShowBox constructor not exported

### ISSUE THREAD

**Issue by conklech** [mikeizbicki/vector-heterogenous#1]
Following along with the README:

```
ghci> import Data.Vector.Heterogenous
ghci> let hvec = vec ShowBox $ "test":::Nothing:::([4,5,6],()):::HNil
<interactive>:27:16: Not in scope: data constructor `ShowBox'
```

Oops; the constructor's not in the export list.

This works:

```
ghci> let hvec = vec (box :: Show a => a -> ShowBox) $ "test":::Nothing:::([4,5,6],()):::HNil
ghci> hvec
vec ShowBox $ "test":::Nothing:::([4,5,6],()):::HNil
```

But the annotation is awkward.

**Comment by mikeizbicki** [comment]
Whoops!  The examples were written for the latest version on git, which I hadn't uploaded to hackage yet.  I just pushed the latest version, so it should all be good now.
