### ISSUE TITLE
The `view` function is missing

### ISSUE THREAD

**Issue by nikita-volkov** [mikeizbicki/vector-heterogenous#2]
In the readme [you refer to the function `view`](https://github.com/mikeizbicki/vector-heterogenous/#advantages-over-hlists), but it's not exported by the library.

**Comment by mikeizbicki** [comment]
Whoops!  I accidentally took it out while doing some updates.  

I've exported it and pushed the fixed version to hackage.

**Comment by nikita-volkov** [comment]
Probably the fastest bugfix in my experience. I appreciate your approach! )

BTW, I very much appreciate some ideas behind your library: the fast lookup, the boxing type - this will definitely find utilization in my work. I hope this project will evolve.

**Comment by mikeizbicki** [comment]
Thanks :)

I'm eventually hoping to build a general "type-level" lens system similar to the lens package built off of this, but that probably won't happen any time soon.
