### ISSUE TITLE
vector-heterogenous fails to parse 1.0.0 and above (Linux x86_64)

### ISSUE THREAD

**Issue by ghost** [mikeizbicki/vector-heterogenous#3]
Hello,

I have ghc `7.4.1`, `base 4.5.0.0`, and `vector 0.10.9.1`. I tried to install vector-heterogenous as a dependency of HLearn, but it failed to parse this package.

```
~$ cabal install vector-heterogenous
Resolving dependencies...
Configuring vector-heterogenous-0.1.2...
Building vector-heterogenous-0.1.2...
Preprocessing library vector-heterogenous-0.1.2...

src/Data/Vector/Heterogenous/HList.hs:51:12:
    parse error on input `('
cabal: Error: some packages failed to install:
vector-heterogenous-0.1.2 failed during the building phase. The exception was:
ExitFailure 1
```

Edit:

On second glance it seems that I may need to have a newer version of GHC?

**Comment by mikeizbicki** [comment]
It requires GHC >= 7.6 to handle the fancy type signatures

**Comment by ghost** [comment]
It works perfectly, my apologies for not realizing that `vector-heterogenous` required ghc `>= 7.6`.
